spring.application.name=apuestas

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=jdbc:sqlserver://SQL1001.site4now.net;databaseName=db_aca4dc_mundial2026;Encrypt=True;TrustServerCertificate=True;
spring.datasource.username=db_aca4dc_mundial2026_admin
spring.datasource.password=Pentatonix1510
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=your-256-bit-secret-key-for-jwt-signatures-should-be-very-long
jwt.expiration=86400000
jwt.refresh.expiration=604800000

# OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha